
import React from 'react';
import { TransactionInfo } from '../types';
import { BitcoinRpcService } from '../services/bitcoinRpc';
import { GeminiService } from '../services/gemini';

interface TransactionDetailsProps {
  txid: string;
  onBlockClick: (hash: string) => void;
  onBack: () => void;
}

export const TransactionDetails: React.FC<TransactionDetailsProps> = ({ txid, onBlockClick, onBack }) => {
  const [tx, setTx] = React.useState<TransactionInfo | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);
  const [aiAnalysis, setAiAnalysis] = React.useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = React.useState(false);

  React.useEffect(() => {
    const fetchTx = async () => {
      try {
        setLoading(true);
        const data = await BitcoinRpcService.getRawTransaction(txid);
        setTx(data);
      } catch (err: any) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };
    fetchTx();
  }, [txid]);

  const handleAiAnalysis = async () => {
    if (!tx) return;
    setIsAnalyzing(true);
    const analysis = await GeminiService.analyzeBlockchainData('transaction', tx);
    setAiAnalysis(analysis);
    setIsAnalyzing(false);
  };

  if (loading) return (
    <div className="flex flex-col items-center justify-center py-24 gap-4">
      <div className="w-12 h-12 border-4 border-orange-500/20 border-t-orange-500 rounded-full animate-spin"></div>
      <p className="text-slate-500 font-bold uppercase tracking-[0.2em] text-xs">Decoding Transaction</p>
    </div>
  );

  if (error || !tx) return (
    <div className="bg-red-500/5 border border-red-500/20 text-red-500 p-10 rounded-3xl text-center max-w-xl mx-auto">
      <h2 className="text-xl font-black mb-2 uppercase tracking-tight">TXID Not Found</h2>
      <p className="mb-8 opacity-70 text-sm leading-relaxed">{error}.</p>
      <button onClick={onBack} className="bg-slate-800 hover:bg-slate-700 px-8 py-3 rounded-2xl text-xs font-black uppercase tracking-widest transition-all">Go Back</button>
    </div>
  );

  const totalOutput = tx.vout.reduce((sum, vo) => sum + vo.value, 0);

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-right-4 duration-500">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="flex items-center gap-5">
          <button 
            onClick={onBack}
            className="p-3.5 hover:bg-slate-800 rounded-2xl border border-slate-700/50 transition-all active:scale-95 bg-slate-900/50"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
          </button>
          <h2 className="text-3xl font-black text-white tracking-tighter uppercase">Transaction <span className="text-orange-500">Detail</span></h2>
        </div>
        
        {!aiAnalysis && !isAnalyzing && (
          <button 
            onClick={handleAiAnalysis}
            className="bg-gradient-to-br from-blue-600 to-cyan-600 hover:from-blue-500 hover:to-cyan-500 text-white px-8 py-3.5 rounded-2xl font-black text-xs uppercase tracking-widest shadow-xl shadow-blue-500/20 transition-all flex items-center gap-3 active:scale-95"
          >
            <span>🤖</span> Analyze Logic
          </button>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-8">
          <div className="bg-slate-800/30 border border-slate-700/50 rounded-[2rem] p-6 md:p-10 backdrop-blur-sm relative overflow-hidden">
            <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500/5 rounded-full blur-[100px] -mr-32 -mt-32"></div>
            <div className="flex flex-wrap items-center justify-between gap-4 mb-8">
              <h3 className="text-lg font-black flex items-center gap-3 text-slate-100 uppercase tracking-widest">
                <span className="w-2.5 h-2.5 rounded-full bg-blue-500 shadow-[0_0_12px_rgba(59,130,246,0.6)]"></span>
                Summary
              </h3>
              <div className="bg-green-500/10 text-green-500 text-[10px] font-black px-4 py-1.5 rounded-full border border-green-500/20 uppercase tracking-[0.2em]">
                {tx.confirmations} Confirmations
              </div>
            </div>
            
            <div className="space-y-1">
              <DetailRow 
                label="Transaction ID" 
                value={tx.txid} 
                isMono 
                isCopyable 
                tooltip="The unique identifier for this transaction, generated by hashing the transaction data."
              />
              <DetailRow 
                label="Block Hash" 
                value={tx.blockhash} 
                isLink 
                onLinkClick={() => onBlockClick(tx.blockhash)} 
                isMono 
                tooltip="The cryptographic hash of the block that contains this transaction."
              />
              <DetailRow 
                label="Total Output" 
                value={`${totalOutput.toFixed(8)} BTC`} 
                tooltip="The total amount of Bitcoin sent, including the intended payment and any change returned to the sender."
              />
              <DetailRow 
                label="Size" 
                value={`${tx.size} bytes`} 
                tooltip="The physical size of the transaction in bytes."
              />
              <DetailRow 
                label="Virtual Size" 
                value={`${tx.vsize} vB`} 
                tooltip="Virtual Size (vSize) counts SegWit witness data as 1 unit and other data as 4 units. This is the metric used for fee calculation."
              />
              <DetailRow 
                label="Weight" 
                value={`${tx.weight}`} 
                tooltip="Weight Units define a transaction's cost to the network. 1 vByte = 4 Weight Units. Blocks are limited to 4,000,000 WU."
              />
              <DetailRow 
                label="Locktime" 
                value={tx.locktime.toString()} 
                tooltip="Specifies the earliest block height or time that a transaction can be added to the blockchain."
              />
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="bg-slate-800/30 border border-slate-700/50 rounded-[2rem] overflow-hidden flex flex-col shadow-xl backdrop-blur-sm">
              <div className="p-6 bg-slate-900/50 border-b border-slate-700/50 font-black text-[10px] uppercase tracking-[0.3em] text-slate-500">Inputs ({tx.vin.length})</div>
              <div className="flex-1 max-h-[400px] overflow-y-auto p-6 space-y-4 custom-scrollbar">
                {tx.vin.map((input, idx) => (
                  <div key={idx} className="bg-slate-900/40 p-4 rounded-2xl border border-slate-700/30 text-xs hover:border-orange-500/30 transition-all group">
                    {input.coinbase ? (
                      <div className="text-orange-500 font-black uppercase tracking-[0.2em] text-[10px]">Coinbase Generation</div>
                    ) : (
                      <>
                        <div className="text-slate-600 mb-2 flex justify-between font-black uppercase tracking-widest text-[9px]">
                          <span>Reference Index</span>
                          <span className="text-slate-400">#{input.vout}</span>
                        </div>
                        <div className="mono text-slate-400 break-all leading-tight bg-black/30 p-3 rounded-xl text-[10px] group-hover:text-slate-200 transition-colors">
                          {input.txid}
                        </div>
                      </>
                    )}
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-slate-800/30 border border-slate-700/50 rounded-[2rem] overflow-hidden flex flex-col shadow-xl backdrop-blur-sm">
              <div className="p-6 bg-slate-900/50 border-b border-slate-700/50 font-black text-[10px] uppercase tracking-[0.3em] text-slate-500">Outputs ({tx.vout.length})</div>
              <div className="flex-1 max-h-[400px] overflow-y-auto p-6 space-y-4 custom-scrollbar">
                {tx.vout.map((output, idx) => (
                  <div key={idx} className="bg-slate-900/40 p-4 rounded-2xl border border-slate-700/30 text-xs hover:border-blue-500/30 transition-all group">
                    <div className="flex justify-between items-center mb-3">
                      <span className="text-orange-500 font-black text-sm">{output.value.toFixed(8)} BTC</span>
                      <span className="bg-slate-800/80 px-2 py-0.5 rounded text-[9px] font-black text-slate-500 uppercase">vout #{idx}</span>
                    </div>
                    <div>
                      <div className="text-slate-600 mb-1.5 text-[9px] uppercase font-black tracking-widest">Recipient</div>
                      <div className="mono text-blue-400 break-all bg-blue-500/5 p-3 rounded-xl border border-blue-500/10 group-hover:bg-blue-500/10 transition-all">
                        {output.scriptPubKey.address || output.scriptPubKey.addresses?.[0] || 'Unparsed Script'}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        <div className="space-y-8">
          <div className="bg-slate-900 border border-slate-700/80 rounded-[2rem] p-8 shadow-2xl relative overflow-hidden group">
            <div className="absolute top-0 right-0 p-12 bg-blue-500/5 rounded-full blur-3xl -mr-16 -mt-16 transition-all group-hover:bg-blue-500/10"></div>
            
            <div className="relative z-10">
              <div className="flex items-center justify-between mb-8">
                <h3 className="text-lg font-black flex items-center gap-3">
                  <span className="text-blue-400 font-bold">SOLUF</span> AI ANALYST
                </h3>
              </div>
              
              {isAnalyzing && (
                <div className="flex flex-col items-center gap-6 py-10 text-blue-300">
                  <div className="w-10 h-10 border-4 border-blue-400 border-t-transparent rounded-full animate-spin"></div>
                  <span className="text-[10px] font-black uppercase tracking-[0.3em] opacity-50">Decoding Inputs...</span>
                </div>
              )}

              {aiAnalysis ? (
                <div className="space-y-6">
                  <div className="prose prose-invert prose-sm max-w-none">
                    <p className="text-slate-300 leading-relaxed whitespace-pre-wrap font-medium text-[13px] border-l-2 border-blue-500/30 pl-4 italic">
                      {aiAnalysis}
                    </p>
                  </div>
                  <button 
                    onClick={() => setAiAnalysis(null)}
                    className="w-full mt-6 text-[10px] font-black uppercase tracking-[0.3em] text-slate-600 hover:text-slate-400 transition-colors py-2"
                  >
                    Reset Analysis
                  </button>
                </div>
              ) : !isAnalyzing ? (
                <div className="text-center py-6">
                  <p className="text-sm text-slate-500 leading-relaxed mb-8">
                    Get an AI summary of this transaction's purpose, potential change outputs, and script security.
                  </p>
                  <button 
                    onClick={handleAiAnalysis}
                    className="w-full bg-slate-800 hover:bg-slate-700 border border-slate-700 text-[10px] font-black uppercase tracking-[0.2em] py-4 rounded-2xl transition-all shadow-lg active:scale-95"
                  >
                    Analyze Logic
                  </button>
                </div>
              ) : null}
            </div>
          </div>

          <div className="bg-slate-800/20 border border-slate-700/50 p-8 rounded-[2rem]">
            <h4 className="text-[10px] font-black text-slate-600 uppercase tracking-[0.3em] mb-6">Serialized Data</h4>
            <div className="bg-black/30 p-5 rounded-2xl mono text-[10px] break-all leading-relaxed text-slate-500/70 max-h-[200px] overflow-y-auto custom-scrollbar italic">
              {tx.hex}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

const DetailRow: React.FC<{ 
  label: string; 
  value: string; 
  isMono?: boolean; 
  isCopyable?: boolean; 
  isLink?: boolean;
  onLinkClick?: () => void;
  tooltip?: string;
}> = ({ label, value, isMono, isCopyable, isLink, onLinkClick, tooltip }) => (
  <div className="flex flex-col sm:flex-row sm:items-center py-4 border-b border-slate-700/20 last:border-0 gap-2 sm:gap-8 group/row">
    <div className="flex items-center gap-2 min-w-[160px]">
      <span className="text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</span>
      {tooltip && (
        <div className="relative group/tooltip">
          <div className="cursor-help text-slate-700 hover:text-slate-400 transition-colors p-1">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <div className="absolute bottom-full left-0 mb-3 hidden group-hover/tooltip:block w-64 p-4 bg-slate-900 border border-slate-700 text-[11px] leading-relaxed text-slate-300 rounded-2xl shadow-2xl z-[100] backdrop-blur-xl animate-in fade-in slide-in-from-bottom-2 duration-200">
            <div className="font-black text-blue-500 mb-2 uppercase text-[9px] tracking-[0.2em]">{label}</div>
            {tooltip}
            <div className="absolute -bottom-1.5 left-4 w-3 h-3 bg-slate-900 border-r border-b border-slate-700 rotate-45"></div>
          </div>
        </div>
      )}
    </div>
    <div className="flex-1 flex items-center gap-3 overflow-hidden">
      <span 
        className={`text-sm break-all leading-relaxed transition-all ${isMono ? 'mono text-slate-400' : 'font-bold text-slate-200'} ${isLink ? 'text-orange-500 hover:text-orange-400 cursor-pointer underline underline-offset-4 decoration-orange-500/20' : ''}`}
        onClick={isLink ? onLinkClick : undefined}
      >
        {value}
      </span>
      {isCopyable && (
        <button 
          onClick={() => {
            navigator.clipboard.writeText(value);
          }}
          className="text-slate-700 hover:text-orange-500 p-2 hover:bg-orange-500/5 rounded-xl transition-all shrink-0"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 00-2 2v8a2 2 0 002 2z" />
          </svg>
        </button>
      )}
    </div>
  </div>
);
